// FHS-664: build a Postman collection (v2.1) and its environments from the
// OpenAPI spec, so the test collection can never drift from the documented
// API. Regenerated by `pnpm -F api openapi:generate`; `openapi:check` fails
// when the committed files are stale.

import type { OpenApiSpec } from './build-spec.js';

type Json = Record<string, unknown>;

const METHODS = ['get', 'post', 'put', 'patch', 'delete'] as const;

export const POSTMAN_ENVIRONMENTS = {
  local: 'http://localhost:3001',
  staging: 'https://api-staging-5500.up.railway.app',
} as const;

// Supabase project that signs parents in. Public: it ships in the web app.
const SUPABASE_URL = 'https://maolytpqazmykjzdybtj.supabase.co';

const DESCRIPTION = [
  'Family Hub API, generated from apps/api/openapi.json. Do not edit by hand:',
  'run `pnpm -F api openapi:generate` after any API change.',
  '',
  '**Get a parent token (folder 01):** set `supabaseAnonKey` and `signInEmail`, send',
  '"Send sign-in email" (or "Send sign-up email" for a new parent). Copy the link in the',
  'email (do not click it: a click uses it up), paste it into `emailLink`, then send',
  '"Verify email link". It saves `userToken`.',
  'A new parent then creates their family with POST /api/public/tenant (folder 04).',
  '',
  'Other variables:',
  '- `tenantSlug`: the family web address, e.g. `khan-family`.',
  '- `kidToken`: saved by POST /api/auth/kid-pin (needs `kidMemberId` and `kidPin`).',
  '- `*Id` variables: the id of the record a request acts on.',
].join('\n');

// Folder per tag, in the order a tester meets them. Unlisted tags sort last.
const FOLDERS: Array<[tag: string, name: string]> = [
  ['system', '00 Health checks'],
  ['signin', '01 Parent sign-in and sign-up (Supabase)'],
  ['auth', '02 Kid PIN sign-in'],
  ['public', '03 Public pages (no sign-in)'],
  ['onboarding', '04 Family setup'],
  ['me', '05 My account'],
  ['members', '06 Family members'],
  ['invitations', '07 Invitations'],
  ['dashboard', '08 Today dashboard'],
  ['tasks', '09 Tasks'],
  ['assignments', '10 Chore assignments'],
  ['habits', '11 Habits and stickers'],
  ['events', '12 Calendar events'],
  ['calendar', '13 Calendar sync feed'],
  ['meals', '14 Meal planner'],
  ['notices', '15 Notice board'],
  ['journal', '16 Journal'],
  ['rewards', '17 Rewards shop'],
  ['reward-config', '18 Reward settings'],
  ['my-world', "19 Kids' money (My World)"],
  ['learn', '20 Learning insights'],
  ['feedback', '21 Feedback'],
  ['admin', '22 Family settings (admin)'],
  ['kid', '23 Kid app (kid token)'],
];

/** Requests to Supabase that sign a parent in and save `userToken`. */
function signInFolder(): Json[] {
  const supabase = (path: string) => ({
    raw: `{{supabaseUrl}}/auth/v1/${path}`,
    host: ['{{supabaseUrl}}'],
    path: ['auth', 'v1', path],
  });
  const headers = [
    { key: 'apikey', value: '{{supabaseAnonKey}}' },
    { key: 'Content-Type', value: 'application/json' },
  ];
  const json = (body: Json) => ({
    mode: 'raw',
    raw: JSON.stringify(body, null, 2),
    options: { raw: { language: 'json' } },
  });
  const sendEmail = (name: string, createUser: boolean, about: string): Json => ({
    name,
    request: {
      method: 'POST',
      auth: { type: 'noauth' },
      header: headers,
      url: supabase('otp'),
      body: json({ email: '{{signInEmail}}', create_user: createUser }),
      description: `${about}\n\n**Sign-in:** none (Supabase public key)\n**Success:** 200`,
    },
    event: [
      {
        listen: 'test',
        script: {
          type: 'text/javascript',
          exec: ["pm.test('returns 200', () => pm.response.to.have.status(200));"],
        },
      },
    ],
  });
  return [
    sendEmail(
      'Send sign-in email',
      false,
      'Emails a sign-in link to an existing parent at `signInEmail`.',
    ),
    sendEmail(
      'Send sign-up email (new parent)',
      true,
      'Creates the parent account if needed and emails a confirmation link to `signInEmail`.',
    ),
    {
      name: 'Verify email link',
      request: {
        method: 'POST',
        auth: { type: 'noauth' },
        header: headers,
        url: supabase('verify'),
        body: json({ type: '{{emailLinkType}}', token_hash: '{{emailTokenHash}}' }),
        description:
          'Copy the whole link from the email (do not click it) into `emailLink` first. Saves `userToken` for every parent request.\n\n**Sign-in:** none (Supabase public key)\n**Success:** 200',
      },
      event: [
        {
          listen: 'prerequest',
          script: {
            type: 'text/javascript',
            exec: [
              "const link = new URL(pm.environment.get('emailLink'));",
              "pm.environment.set('emailTokenHash', link.searchParams.get('token'));",
              "pm.environment.set('emailLinkType', link.searchParams.get('type') || 'magiclink');",
            ],
          },
        },
        {
          listen: 'test',
          script: {
            type: 'text/javascript',
            exec: [
              "pm.test('returns 200', () => pm.response.to.have.status(200));",
              "if (pm.response.code === 200) pm.environment.set('userToken', pm.response.json().access_token);",
            ],
          },
        },
      ],
    },
  ];
}

// Path parameters whose own name would be vague as an environment variable.
const RENAMED_PARAMS: Record<string, string> = {
  slug: 'tenantSlug',
  token: 'calendarFeedToken',
  key: 'settingKey',
  subject: 'learnSubject',
};

/** `{memberId}` style name for a path parameter, from the segment before it. */
function variableFor(param: string, segments: string[], index: number): string {
  if (param !== 'id') return RENAMED_PARAMS[param] ?? param;
  const owner = (segments[index - 1] ?? 'item').replace(/[^A-Za-z0-9]+(.)/g, (_, c: string) =>
    c.toUpperCase(),
  );
  const singular = owner.endsWith('ies')
    ? `${owner.slice(0, -3)}y`
    : owner.endsWith('s')
      ? owner.slice(0, -1)
      : owner;
  return `${singular}Id`;
}

/** A small, valid sample value for a JSON schema, used as the request body. */
export function sampleFor(schema: unknown, depth = 0): unknown {
  if (!schema || typeof schema !== 'object' || depth > 6) return null;
  const s = schema as Json;
  if ('default' in s) return s['default'];
  if (Array.isArray(s['enum'])) return s['enum'][0];
  if ('const' in s) return s['const'];
  for (const k of ['anyOf', 'oneOf', 'allOf'] as const) {
    const list = s[k];
    if (Array.isArray(list) && list.length) {
      const pick = list.find((x) => (x as Json)['type'] !== 'null') ?? list[0];
      return sampleFor(pick, depth + 1);
    }
  }
  const type = Array.isArray(s['type'])
    ? (s['type'] as string[]).find((t) => t !== 'null')
    : (s['type'] as string | undefined);
  switch (type) {
    case 'object': {
      const props = (s['properties'] ?? {}) as Record<string, unknown>;
      const required = new Set((s['required'] as string[] | undefined) ?? Object.keys(props));
      return Object.fromEntries(
        Object.entries(props)
          .filter(([k]) => required.has(k))
          .map(([k, v]) => [k, sampleFor(v, depth + 1)]),
      );
    }
    case 'array': {
      const min = (s['minItems'] as number | undefined) ?? 0;
      return min > 0 ? [sampleFor(s['items'], depth + 1)] : [];
    }
    case 'string': {
      const format = s['format'];
      if (format === 'uuid') return '00000000-0000-4000-8000-000000000000';
      if (format === 'date') return '2099-01-01';
      if (format === 'date-time') return '2099-01-01T09:00:00Z';
      if (format === 'email') return 'parent@example.com';
      if (format === 'uri' || format === 'url') return 'https://example.com';
      const min = (s['minLength'] as number | undefined) ?? 1;
      return 'x'.repeat(Math.max(1, Math.min(min, 8)));
    }
    case 'integer':
    case 'number':
      return (s['minimum'] as number | undefined) ?? 1;
    case 'boolean':
      return false;
    default:
      return null;
  }
}

function successCode(op: Json): string {
  const codes = Object.keys((op['responses'] ?? {}) as Json);
  return codes.find((c) => c.startsWith('2')) ?? '200';
}

const AUTH_LABEL: Record<string, string> = {
  bearerAuth: 'parent or adult token (`userToken`)',
  kidAuth: 'kid token (`kidToken`)',
};

/** The request's description panel: what it does, sign-in needed, expected status. */
function describe(op: Json, scheme: string | undefined): string {
  const lines = [(op['summary'] as string | undefined) ?? ''];
  if (op['description']) lines.push('', op['description'] as string);
  lines.push(
    '',
    `**Sign-in:** ${scheme ? (AUTH_LABEL[scheme] ?? scheme) : 'none'}`,
    `**Success:** ${successCode(op)}`,
  );
  return lines.join('\n');
}

function requestItem(path: string, method: string, op: Json): Json {
  const segments = path.split('/').filter(Boolean);
  const pathVars: Json[] = [];
  const rawPath = segments
    .map((seg, i) => {
      const m = /^\{(.+)\}$/.exec(seg);
      if (!m) return seg;
      const name = m[1] as string;
      pathVars.push({ key: name, value: `{{${variableFor(name, segments, i)}}}` });
      return `:${name}`;
    })
    .join('/');

  const params = (op['parameters'] ?? []) as Json[];
  const query = params
    .filter((p) => p['in'] === 'query')
    .map((p) => ({
      key: p['name'],
      value: '',
      description: p['description'] ?? '',
      disabled: !p['required'],
    }));
  const headers: Json[] = [];
  if (params.some((p) => p['in'] === 'header' && p['name'] === 'x-tenant-slug')) {
    headers.push({ key: 'x-tenant-slug', value: '{{tenantSlug}}' });
  }

  const security = op['security'] as Array<Record<string, unknown>> | undefined;
  const scheme = security?.[0] ? Object.keys(security[0])[0] : undefined;
  const auth =
    scheme === 'kidAuth'
      ? { type: 'bearer', bearer: [{ key: 'token', value: '{{kidToken}}', type: 'string' }] }
      : scheme === 'bearerAuth'
        ? { type: 'bearer', bearer: [{ key: 'token', value: '{{userToken}}', type: 'string' }] }
        : { type: 'noauth' };

  const request: Json = {
    method: method.toUpperCase(),
    auth,
    header: headers,
    url: {
      raw: `{{baseUrl}}/${rawPath}`,
      host: ['{{baseUrl}}'],
      path: rawPath.split('/'),
      ...(query.length ? { query } : {}),
      ...(pathVars.length ? { variable: pathVars } : {}),
    },
    description: describe(op, scheme),
  };

  const body = (op['requestBody'] as Json | undefined)?.['content'] as Json | undefined;
  const bodySchema = (body?.['application/json'] as Json | undefined)?.['schema'];
  if (bodySchema) {
    headers.push({ key: 'Content-Type', value: 'application/json' });
    request['body'] = {
      mode: 'raw',
      raw: JSON.stringify(sampleFor(bodySchema), null, 2),
      options: { raw: { language: 'json' } },
    };
  }

  const code = successCode(op);
  const tests = [`pm.test('returns ${code}', () => pm.response.to.have.status(${code}));`];
  if (path === '/api/auth/kid-pin' && method === 'post') {
    // Saves the kid session for every /api/kid request that follows.
    tests.push(
      "if (pm.response.code === 200) pm.environment.set('kidToken', pm.response.json().token);",
    );
    request['body'] = {
      mode: 'raw',
      raw: JSON.stringify(
        { tenantSlug: '{{tenantSlug}}', memberId: '{{kidMemberId}}', pin: '{{kidPin}}' },
        null,
        2,
      ),
      options: { raw: { language: 'json' } },
    };
  }

  // Postman shows the method as a badge, so the path alone is the name.
  return {
    name: path,
    request,
    event: [{ listen: 'test', script: { type: 'text/javascript', exec: tests } }],
  };
}

export function buildPostmanCollection(spec: OpenApiSpec): Json {
  const folders = new Map<string, Json[]>([['signin', signInFolder()]]);
  for (const [path, ops] of Object.entries(spec.paths)) {
    for (const method of METHODS) {
      const op = ops[method] as Json | undefined;
      if (!op) continue;
      const tag = ((op['tags'] as string[] | undefined) ?? ['other'])[0] as string;
      if (!folders.has(tag)) folders.set(tag, []);
      folders.get(tag)!.push(requestItem(path, method, op));
    }
  }
  return {
    info: {
      name: 'Family Hub API',
      description: DESCRIPTION,
      schema: 'https://schema.getpostman.com/json/collection/v2.1.0/collection.json',
    },
    item: [...folders.entries()]
      .map(([tag, item]) => ({ name: FOLDERS.find(([t]) => t === tag)?.[1] ?? tag, item }))
      .sort((a, b) => a.name.localeCompare(b.name)),
  };
}

/** Every `{{variable}}` the collection uses, so the environments list them all. */
export function collectionVariables(collection: Json): string[] {
  const found = new Set<string>();
  for (const m of JSON.stringify(collection).matchAll(/\{\{([A-Za-z0-9_]+)\}\}/g)) {
    found.add(m[1] as string);
  }
  return [...found].sort();
}

const SECRET = new Set(['userToken', 'kidToken', 'kidPin', 'supabaseAnonKey']);

export function buildPostmanEnvironment(
  name: keyof typeof POSTMAN_ENVIRONMENTS,
  variables: string[],
  filled: Record<string, string> = {},
): Json {
  return {
    name: `Family Hub ${name}`,
    values: variables.map((key) => ({
      key,
      value:
        key === 'baseUrl'
          ? POSTMAN_ENVIRONMENTS[name]
          : key === 'supabaseUrl'
            ? SUPABASE_URL
            : (filled[key] ?? ''),
      type: SECRET.has(key) ? 'secret' : 'default',
      enabled: true,
    })),
  };
}

/**
 * File name → contents for everything under apps/api/postman/. `filled`
 * pre-sets environment values; only the local, gitignored copy passes any.
 */
export function buildPostmanFiles(
  spec: OpenApiSpec,
  filled: Record<string, string> = {},
): Record<string, string> {
  const collection = buildPostmanCollection(spec);
  const extra = ['kidMemberId', 'kidPin', 'emailLink'];
  const vars = [...new Set([...collectionVariables(collection), ...extra])].sort();
  const files: Record<string, string> = {
    'family-hub-api.postman_collection.json': JSON.stringify(collection, null, 2) + '\n',
  };
  for (const env of Object.keys(POSTMAN_ENVIRONMENTS) as Array<keyof typeof POSTMAN_ENVIRONMENTS>) {
    files[`${env}.postman_environment.json`] =
      JSON.stringify(buildPostmanEnvironment(env, vars, filled), null, 2) + '\n';
  }
  return files;
}
