// FHS-664: build a Postman collection (v2.1) and its environments from the
// OpenAPI spec, so the test collection can never drift from the documented
// API. Regenerated by `pnpm -F api openapi:generate`; `openapi:check` fails
// when the committed files are stale.

import type { OpenApiSpec } from './build-spec.js';

type Json = Record<string, unknown>;

const METHODS = ['get', 'post', 'put', 'patch', 'delete'] as const;

export const POSTMAN_ENVIRONMENTS = {
  local: 'http://localhost:3001',
  staging: 'https://api-staging-5500.up.railway.app',
} as const;

const DESCRIPTION = [
  'Family Hub API, generated from apps/api/openapi.json. Do not edit by hand:',
  'run `pnpm -F api openapi:generate` after any API change.',
  '',
  'Set these environment variables before sending requests:',
  '- `userToken`: a parent or adult sign-in token. Sign in to the web app, then',
  '  copy `access_token` from the `sb-...-auth-token` entry in the browser storage.',
  '- `tenantSlug`: the family web address, e.g. `khan-family`.',
  '- `kidToken`: filled automatically by "Exchange a kid PIN" (needs `kidMemberId`',
  '  and `kidPin`).',
  '- `*Id` variables: the id of the record a request acts on.',
].join('\n');

// Path parameters whose own name would be vague as an environment variable.
const RENAMED_PARAMS: Record<string, string> = {
  slug: 'tenantSlug',
  token: 'calendarFeedToken',
  key: 'settingKey',
  subject: 'learnSubject',
};

/** `{memberId}` style name for a path parameter, from the segment before it. */
function variableFor(param: string, segments: string[], index: number): string {
  if (param !== 'id') return RENAMED_PARAMS[param] ?? param;
  const owner = (segments[index - 1] ?? 'item').replace(/[^A-Za-z0-9]+(.)/g, (_, c: string) =>
    c.toUpperCase(),
  );
  const singular = owner.endsWith('ies')
    ? `${owner.slice(0, -3)}y`
    : owner.endsWith('s')
      ? owner.slice(0, -1)
      : owner;
  return `${singular}Id`;
}

/** A small, valid sample value for a JSON schema, used as the request body. */
export function sampleFor(schema: unknown, depth = 0): unknown {
  if (!schema || typeof schema !== 'object' || depth > 6) return null;
  const s = schema as Json;
  if ('default' in s) return s['default'];
  if (Array.isArray(s['enum'])) return s['enum'][0];
  if ('const' in s) return s['const'];
  for (const k of ['anyOf', 'oneOf', 'allOf'] as const) {
    const list = s[k];
    if (Array.isArray(list) && list.length) {
      const pick = list.find((x) => (x as Json)['type'] !== 'null') ?? list[0];
      return sampleFor(pick, depth + 1);
    }
  }
  const type = Array.isArray(s['type'])
    ? (s['type'] as string[]).find((t) => t !== 'null')
    : (s['type'] as string | undefined);
  switch (type) {
    case 'object': {
      const props = (s['properties'] ?? {}) as Record<string, unknown>;
      const required = new Set((s['required'] as string[] | undefined) ?? Object.keys(props));
      return Object.fromEntries(
        Object.entries(props)
          .filter(([k]) => required.has(k))
          .map(([k, v]) => [k, sampleFor(v, depth + 1)]),
      );
    }
    case 'array': {
      const min = (s['minItems'] as number | undefined) ?? 0;
      return min > 0 ? [sampleFor(s['items'], depth + 1)] : [];
    }
    case 'string': {
      const format = s['format'];
      if (format === 'uuid') return '00000000-0000-4000-8000-000000000000';
      if (format === 'date') return '2099-01-01';
      if (format === 'date-time') return '2099-01-01T09:00:00Z';
      if (format === 'email') return 'parent@example.com';
      if (format === 'uri' || format === 'url') return 'https://example.com';
      const min = (s['minLength'] as number | undefined) ?? 1;
      return 'x'.repeat(Math.max(1, Math.min(min, 8)));
    }
    case 'integer':
    case 'number':
      return (s['minimum'] as number | undefined) ?? 1;
    case 'boolean':
      return false;
    default:
      return null;
  }
}

function successCode(op: Json): string {
  const codes = Object.keys((op['responses'] ?? {}) as Json);
  return codes.find((c) => c.startsWith('2')) ?? '200';
}

function requestItem(path: string, method: string, op: Json): Json {
  const segments = path.split('/').filter(Boolean);
  const pathVars: Json[] = [];
  const rawPath = segments
    .map((seg, i) => {
      const m = /^\{(.+)\}$/.exec(seg);
      if (!m) return seg;
      const name = m[1] as string;
      pathVars.push({ key: name, value: `{{${variableFor(name, segments, i)}}}` });
      return `:${name}`;
    })
    .join('/');

  const params = (op['parameters'] ?? []) as Json[];
  const query = params
    .filter((p) => p['in'] === 'query')
    .map((p) => ({
      key: p['name'],
      value: '',
      description: p['description'] ?? '',
      disabled: !p['required'],
    }));
  const headers: Json[] = [];
  if (params.some((p) => p['in'] === 'header' && p['name'] === 'x-tenant-slug')) {
    headers.push({ key: 'x-tenant-slug', value: '{{tenantSlug}}' });
  }

  const security = op['security'] as Array<Record<string, unknown>> | undefined;
  const scheme = security?.[0] ? Object.keys(security[0])[0] : undefined;
  const auth =
    scheme === 'kidAuth'
      ? { type: 'bearer', bearer: [{ key: 'token', value: '{{kidToken}}', type: 'string' }] }
      : scheme === 'bearerAuth'
        ? { type: 'bearer', bearer: [{ key: 'token', value: '{{userToken}}', type: 'string' }] }
        : { type: 'noauth' };

  const request: Json = {
    method: method.toUpperCase(),
    auth,
    header: headers,
    url: {
      raw: `{{baseUrl}}/${rawPath}`,
      host: ['{{baseUrl}}'],
      path: rawPath.split('/'),
      ...(query.length ? { query } : {}),
      ...(pathVars.length ? { variable: pathVars } : {}),
    },
    description: (op['description'] as string | undefined) ?? '',
  };

  const body = (op['requestBody'] as Json | undefined)?.['content'] as Json | undefined;
  const bodySchema = (body?.['application/json'] as Json | undefined)?.['schema'];
  if (bodySchema) {
    headers.push({ key: 'Content-Type', value: 'application/json' });
    request['body'] = {
      mode: 'raw',
      raw: JSON.stringify(sampleFor(bodySchema), null, 2),
      options: { raw: { language: 'json' } },
    };
  }

  const code = successCode(op);
  const tests = [`pm.test('returns ${code}', () => pm.response.to.have.status(${code}));`];
  if (path === '/api/auth/kid-pin' && method === 'post') {
    // Saves the kid session for every /api/kid request that follows.
    tests.push(
      "if (pm.response.code === 200) pm.environment.set('kidToken', pm.response.json().token);",
    );
    request['body'] = {
      mode: 'raw',
      raw: JSON.stringify(
        { tenantSlug: '{{tenantSlug}}', memberId: '{{kidMemberId}}', pin: '{{kidPin}}' },
        null,
        2,
      ),
      options: { raw: { language: 'json' } },
    };
  }

  return {
    name: (op['summary'] as string | undefined) ?? `${method.toUpperCase()} ${path}`,
    request,
    event: [{ listen: 'test', script: { type: 'text/javascript', exec: tests } }],
  };
}

export function buildPostmanCollection(spec: OpenApiSpec): Json {
  const folders = new Map<string, Json[]>();
  for (const [path, ops] of Object.entries(spec.paths)) {
    for (const method of METHODS) {
      const op = ops[method] as Json | undefined;
      if (!op) continue;
      const tag = ((op['tags'] as string[] | undefined) ?? ['other'])[0] as string;
      if (!folders.has(tag)) folders.set(tag, []);
      folders.get(tag)!.push(requestItem(path, method, op));
    }
  }
  return {
    info: {
      name: 'Family Hub API',
      description: DESCRIPTION,
      schema: 'https://schema.getpostman.com/json/collection/v2.1.0/collection.json',
    },
    item: [...folders.entries()]
      .sort(([a], [b]) => a.localeCompare(b))
      .map(([name, item]) => ({ name, item })),
  };
}

/** Every `{{variable}}` the collection uses, so the environments list them all. */
export function collectionVariables(collection: Json): string[] {
  const found = new Set<string>();
  for (const m of JSON.stringify(collection).matchAll(/\{\{([A-Za-z0-9_]+)\}\}/g)) {
    found.add(m[1] as string);
  }
  return [...found].sort();
}

const SECRET = new Set(['userToken', 'kidToken', 'kidPin']);

export function buildPostmanEnvironment(
  name: keyof typeof POSTMAN_ENVIRONMENTS,
  variables: string[],
): Json {
  return {
    name: `Family Hub ${name}`,
    values: variables.map((key) => ({
      key,
      value: key === 'baseUrl' ? POSTMAN_ENVIRONMENTS[name] : '',
      type: SECRET.has(key) ? 'secret' : 'default',
      enabled: true,
    })),
  };
}

/** File name → contents for everything under apps/api/postman/. */
export function buildPostmanFiles(spec: OpenApiSpec): Record<string, string> {
  const collection = buildPostmanCollection(spec);
  const vars = [...new Set([...collectionVariables(collection), 'kidMemberId', 'kidPin'])].sort();
  const files: Record<string, string> = {
    'family-hub-api.postman_collection.json': JSON.stringify(collection, null, 2) + '\n',
  };
  for (const env of Object.keys(POSTMAN_ENVIRONMENTS) as Array<keyof typeof POSTMAN_ENVIRONMENTS>) {
    files[`${env}.postman_environment.json`] =
      JSON.stringify(buildPostmanEnvironment(env, vars), null, 2) + '\n';
  }
  return files;
}
